### ISSUE TITLE
Exception caught from Prism Launcher 9.1 with RLCraft Dregora

### ISSUE THREAD

**Issue by Qattos** [Radk6/MC-Optimization-Guide#13]
I followed your guide for RLCraft Dregora 1.0.3 to the letter, removed what had to be removed and added what had to be added, used Java 21 and Java 22, but I keep getting this error on launch:

`Exception caught from launcher
java.lang.IllegalAccessException: no such method: net.minecraft.launchwrapper.Launch.main(String[])void/invokeStatic
	at java.base/java.lang.invoke.MemberName.makeAccessException(MemberName.java:911)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:994)
	at java.base/java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:3750)
	at java.base/java.lang.invoke.MethodHandles$Lookup.findStatic(MethodHandles.java:2675)
	at org.prismlauncher.utils.ReflectionUtils.findMainMethod(ReflectionUtils.java:75)
	at org.prismlauncher.utils.ReflectionUtils.findMainMethod(ReflectionUtils.java:88)
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:104)
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129)
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70)
Caused by: java.lang.NoClassDefFoundError: joptsimple/OptionSpec
	at java.base/java.lang.invoke.MethodHandleNatives.resolve(Native Method)
	at java.base/java.lang.invoke.MemberName$Factory.resolve(MemberName.java:962)
	at java.base/java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:991)
	... 7 more
Caused by: java.lang.ClassNotFoundException: joptsimple.OptionSpec
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 10 more
Exiting with ERROR
Process exited with code 2.
`

I can provide any other info if you need it.

**Comment by Radk6** [comment]
Could you upload the entire crash log to mclo.gs and send the link here?

**Comment by Qattos** [comment]
This is the Minecraft log from Prism Launcher:
https://mclo.gs/hgCqO7H

**Comment by Qattos** [comment]
Sorry for bringing this up again, but did the log I provided help in any way?

**Comment by Radk6** [comment]
Okay I decided to test the instructions again and it works fine. From the log you sent I can see that you have all of the mods required for it to work, so I'm not sure why it crashes for you.

One thing you could try is using OptiFine HD U G6_pre1 instead of G5, but I don't think that's the cause of the issue.

**Comment by Qattos** [comment]
I did everything all over again with a new clean instance of RLCraft Dregora, launched it once, exited and moved `libraries` and `patches` folders from Cleanroom zip file into Dregora's instance folder, followed your steps, removing and adding all the suggested mods and disabling and enabling the values you specified in config files, then launched it and got a different error this time, I pasted the error into ChatGPT and it told me that I needed a dependency mod called [Red Core ](https://www.curseforge.com/minecraft/mc-mods/red-core), I installed it and voila! The game launched and I managed to create a world and played for a couple of minutes without any crashes.

This is the [log file](https://mclo.gs/jpQGW0V) of the successful launch in case it helps.
You can close this issue if there's nothing else to add, thank you for your time and effort.
